TRUNCATE TABLE school_schema.students RESTART IDENTITY CASCADE;
TRUNCATE TABLE school_schema.groups RESTART IDENTITY CASCADE;
TRUNCATE TABLE school_schema.courses RESTART IDENTITY CASCADE;
TRUNCATE TABLE school_schema.student_courses RESTART IDENTITY CASCADE;